%% Description prox_toeplitz 
%  Projection onto the set of Toeplitz matrices with sparse kernel 
%  and of unit Frobenius norm.
%
%  Xprox = prox_toeplitz(X,s) projects the input matrix X onto the set of
%  Toeplitz matrices generated by kernels which have at most s non-zero
%  entries and unit Frobenius norm. Xprox is the projection of X onto this
%  set.
%
% For more information on the FAuST Project, please visit the website of 
% the project :  <http://faust.gforge.inria.fr>
%
%% License:
% Copyright (2016):	Luc Le Magoarou, Remi Gribonval
%			INRIA Rennes, FRANCE
%			http://www.inria.fr/
%
% The FAuST Toolbox is distributed under the terms of the GNU Affero 
% General Public License.
% This program is free software: you can redistribute it and/or modify
% it under the terms of the GNU Affero General Public License as published 
% by the Free Software Foundation.
%
% This program is distributed in the hope that it will be useful, but 
% WITHOUT ANY WARRANTY; without even the implied warranty of 
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  
% See the GNU Affero General Public License for more details.
%
% You should have received a copy of the GNU Affero General Public License
% along with this program.  If not, see <http://www.gnu.org/licenses/>.
%
%% Contacts:	
%	Luc Le Magoarou: luc.le-magoarou@inria.fr
%	Remi Gribonval : remi.gribonval@inria.fr
%
%% References:
% [1]	Le Magoarou L. and Gribonval R., "Flexible multi-layer sparse 
%	approximations of matrices and applications", Journal of Selected 
%	Topics in Signal Processing, 2016.
%	<https://hal.archives-ouvertes.fr/hal-01167948v1>
%%


function Xprox = prox_toeplitz(X,s)

[l,r] = size(X);

crit = zeros(l+r-1,1);
vecmean = crit;
vecval = crit;
for i = 1:l+r-1
    crit(i) = numel(diag(X,-l+i))*mean(diag(X,-l+i))^2;
    vecmean(i) = mean(diag(X,-l+i));
end

[~,sortIndex] = sort(crit,'descend');
maxIndex = sortIndex(1:min(round(s),numel(sortIndex)));
vecval(maxIndex) = vecmean(maxIndex);

Xprox = toeplitz(vecval(l:-1:1),vecval(l:end));
Xprox = Xprox/norm(Xprox,'fro');
end


%2*downsample(prox_toeplitz(upsample(X',2)',s)',2)'
%blkdiag([2*downsample(prox_toeplitz(upsample(X1',2)',8)',2)',2*downsample(prox_toeplitz(upsample(X2',2)',8)',2)'],eye(32))