.ctest_template: &ctest_script
    script:
        - ctest -O ctest.log -S ./CDashConfScript.cmake

stages:
        - test
        - test_wrapper

ctest:
    <<: *ctest_script
    variables: {SLOW_TESTS: "OFF"}
    except:
        - schedules
    stage: test

ctest_python:
    <<: *ctest_script
    variables: {BUILD_WRAPPER_PYTHON: "ON", SLOW_TESTS: "OFF"}
    except:
        - schedules
    stage: test_wrapper

ctest_matlab:
    <<: *ctest_script
    variables: {BUILD_WRAPPER_MATLAB: "ON", SLOW_TESTS: "OFF"}
    except:
        - schedules
    stage: test_wrapper

.ctest_nightly: &ctest_nightly_script
    <<: *ctest_script
    variables: {BUILD_WRAPPER_MATLAB: "ON", BUILD_WRAPPER_PYTHON: "ON", SLOW_TESTS: "ON"}
    only:
        - schedules

ctest_nightly_linux:
    <<: *ctest_nightly_script
    tags:
       - linux

ctest_nightly_macos:
    <<: *ctest_nightly_script
    tags:
       - macos

