.ctest_template: &ctest_script
    script:
        - ctest -O ctest.log -S ./CDashConfScript.cmake

stages:
        - test
        - test_wrapper
        - package_rev

ctest:
    <<: *ctest_script
    variables: {SLOW_TESTS: "OFF"}
    except:
        - schedules
        - tags
    stage: test

ctest_python:
    <<: *ctest_script
    variables: {BUILD_WRAPPER_PYTHON: "ON", SLOW_TESTS: "OFF", DONT_PYPLOT_FAUST_TIME: "ON", GIT_STRATEGY: none}
    except:
        - schedules
        - tags
    stage: test_wrapper

ctest_matlab:
    <<: *ctest_script
    variables: {BUILD_WRAPPER_MATLAB: "ON", SLOW_TESTS: "OFF"}
    except:
        - schedules
        - tags
    stage: test_wrapper

.ctest_nightly: &ctest_nightly_script
    <<: *ctest_script
    variables: {BUILD_WRAPPER_MATLAB: "ON", BUILD_WRAPPER_PYTHON: "ON", SLOW_TESTS: "ON", DONT_PYPLOT_FAUST_TIME: "ON"}
    only:
        - schedules

ctest_nightly_linux:
    <<: *ctest_nightly_script
    tags:
       - linux

ctest_nightly_macos:
    <<: *ctest_nightly_script
    tags:
       - macos

ctest_nightly_win7:
    <<: *ctest_script
    variables: {BUILD_WRAPPER_MATLAB: "ON", BUILD_WRAPPER_PYTHON: "OFF", SLOW_TESTS: "ON"}
    only:
        - schedules
    tags:
       - win7

package_macos:
    stage: package_rev
    script:
        - if [[ ! -d 'build' ]]; then  mkdir build;fi; cd build
        - 'cmake -DBUILD_WRAPPER_PYTHON=ON -DBUILD_WRAPPER_MATLAB=ON -DCMAKE_INSTALL_PREFIX=/opt/local/faust-$CI_COMMIT_SHA  ..'
        - make
        - 'echo $MACOS_PASS | sudo -S make install'
        - 'echo $MACOS_PASS | sudo -S hdiutil create -volname Faust-$CI_COMMIT_SHA-MatlabR2016a-Py2.7 -srcfolder /opt/local/faust-$CI_COMMIT_SHA -ov -format UDRW faust-$CI_COMMIT_SHA'
        - pkgbuild --identifier fr.inria.faust --version $CI_COMMIT_SHA --root /opt/local/faust-$CI_COMMIT_SHA --install-location /opt/local/faust-$CI_COMMIT_SHA ./faust-$CI_COMMIT_SHA.pkg
        - if [[ -d $MACOS_PKG_STORE_PATH ]]; then echo $MACOS_PASS | sudo -S mv faust-$CI_COMMIT_SHA.dmg faust-$CI_COMMIT_SHA.pkg $MACOS_PKG_STORE_PATH; fi
    tags:
        - macos
    except:
        - schedules
        - tags

package_linux:
   stage: package_rev
   script:
        - if [[ ! -d 'build' ]]; then  mkdir build;fi; cd build
        - 'cmake -DBUILD_WRAPPER_PYTHON=ON -DBUILD_WRAPPER_MATLAB=ON -DCMAKE_INSTALL_PREFIX=/opt/faust-$CI_COMMIT_SHA -DCPACK_PACKAGE_FILE_NAME=Faust-$CI_COMMIT_SHA ..'
        - make
        - cpack -G RPM -C CPackConfig.cmake
        - cpack -G DEB -C CPackConfig.cmake
        - lftp -u $FTP_SERV_USER,$FTP_SERV_PASS -e 'set ssl:verify-certificate no;mput Faust-*.rpm Faust-*.deb;quit' $FTP_SERV_HOST
        - 'mv Faust-$CI_COMMIT_SHA* $HOME'
   tags:
        - linux
   except:
        - schedules
        - tags

# jobs triggered by git tag don't verify that CMakeLists.txt conforms to the tag name/version but it must use the same version

package_macos_release:
    script:
        - if [[ ! -d 'build' ]]; then  mkdir build;fi; cd build
        - 'cmake -DBUILD_WRAPPER_PYTHON=ON -DBUILD_WRAPPER_MATLAB=ON -DCMAKE_INSTALL_PREFIX=/opt/local/faust-$CI_COMMIT_TAG -DCMAKE_BUILD_TYPE=Release -DEXCLUDE_FAUST_LIB_INSTALL=ON ..'
        - make
        - 'echo $MACOS_PASS | sudo -S make install'
        - 'echo $MACOS_PASS | sudo -S hdiutil create -volname Faust-$CI_COMMIT_TAG-MatlabR2016a-Py2.7 -srcfolder /opt/local/faust-$CI_COMMIT_TAG -ov -format UDRW faust-$CI_COMMIT_TAG'
        - pkgbuild --identifier fr.inria.faust --version $CI_COMMIT_TAG --root /opt/local/faust-$CI_COMMIT_TAG --install-location /opt/local/faust-$CI_COMMIT_TAG ./faust-$CI_COMMIT_TAG.pkg
        - if [[ -d $MACOS_PKG_STORE_PATH ]]; then echo $MACOS_PASS | sudo -S mv faust-$CI_COMMIT_TAG.dmg faust-$CI_COMMIT_TAG.pkg $MACOS_PKG_STORE_PATH; fi
    tags:
        - macos
    only:
        - tags

package_linux_release:
   script:
        - if [[ ! -d 'build' ]]; then  mkdir build;fi; cd build
        - 'cmake -DBUILD_WRAPPER_PYTHON=ON -DBUILD_WRAPPER_MATLAB=ON -DCMAKE_INSTALL_PREFIX=/opt/faust-$CI_COMMIT_TAG -DCPACK_PACKAGE_FILE_NAME=Faust-$CI_COMMIT_TAG -DCMAKE_BUILD_TYPE=Release -DEXCLUDE_FAUST_LIB_INSTALL=ON  ..'
        - make
        - cpack -G RPM -C CPackConfig.cmake
        - cpack -G DEB -C CPackConfig.cmake
        - 'mv Faust-*rpm Faust-*.deb $HOME'
   tags:
        - linux
   only:
        - tags
