.ctest_template: &ctest_script
    script:
        - ctest -O ctest.log -S ./CDashConfScript.cmake

stages:
        - test
        - test_wrapper
        - package_rev

ctest:
    <<: *ctest_script
    variables: {SLOW_TESTS: "OFF"}
    except:
        - schedules
    stage: test

ctest_python:
    <<: *ctest_script
    variables: {BUILD_WRAPPER_PYTHON: "ON", SLOW_TESTS: "OFF", DONT_PYPLOT_FAUST_TIME: "ON", GIT_STRATEGY: none}
    except:
        - schedules
    stage: test_wrapper

ctest_matlab:
    <<: *ctest_script
    variables: {BUILD_WRAPPER_MATLAB: "ON", SLOW_TESTS: "OFF"}
    except:
        - schedules
    stage: test_wrapper

.ctest_nightly: &ctest_nightly_script
    <<: *ctest_script
    variables: {BUILD_WRAPPER_MATLAB: "ON", BUILD_WRAPPER_PYTHON: "ON", SLOW_TESTS: "ON", DONT_PYPLOT_FAUST_TIME: "ON"}
    only:
        - schedules

ctest_nightly_linux:
    <<: *ctest_nightly_script
    tags:
       - linux

ctest_nightly_macos:
    <<: *ctest_nightly_script
    tags:
       - macos

ctest_nightly_win7:
    <<: *ctest_script
    variables: {BUILD_WRAPPER_MATLAB: "ON", BUILD_WRAPPER_PYTHON: "OFF", SLOW_TESTS: "ON"}
    only:
        - schedules
    tags:
       - win7

package_macos:
    stage: package_rev
    script:
        - if [[ ! -d 'build' ]]; then  mkdir build;fi; cd build
        - 'cmake -DBUILD_WRAPPER_PYTHON=ON -DBUILD_WRAPPER_MATLAB=ON -DCMAKE_INSTALL_PREFIX=/opt/local/faust-$CI_COMMIT_SHA  ..'
        - make
        - 'echo $MACOS_PASS | sudo -S make install'
        - 'echo $MACOS_PASS | sudo -S hdiutil create -volname Faust-MatlabR2016a-Py2.7-$CI_COMMIT_SHA -srcfolder /opt/local/faust-$CI_COMMIT_SHA -ov -format UDRW faust-$CI_COMMIT_SHA'
        - if [[ -d $MACOS_PKG_STORE_PATH ]]; then echo $MACOS_PASS | sudo -S mv faust-$CI_COMMIT_SHA.dmg $MACOS_PKG_STORE_PATH; fi
    tags:
        - macos
    except:
        - schedules

package_linux:
   stage: package_rev
   script:
        - if [[ ! -d 'build' ]]; then  mkdir build;fi; cd build
        - 'cmake -DBUILD_WRAPPER_PYTHON=ON -DBUILD_WRAPPER_MATLAB=ON -DCMAKE_INSTALL_PREFIX=/opt/faust -DCPACK_PACKAGE_FILE_NAME=Faust-$CI_COMMIT_SHA ..'
        - make
        - cpack -G RPM -C CPackConfig.cmake
        - cpack -G DEB -C CPackConfig.cmake
        - 'mv Faust-$CI_COMMIT_SHA* $HOME'
   tags:
        - linux
   except:
        - schedules
