FROM fedora:37
WORKDIR faust
RUN dnf -y install python3 python3-devel python3-numpy python3-scipy matio matio-devel
RUN dnf -y install clang
RUN dnf -y install cmake
RUN dnf -y install eigen3
RUN dnf -y install Cython
