set(CTEST_PROJECT_NAME "faust")
set(CTEST_NIGHTLY_START_TIME "18:30:00 CET")
set(CTEST_DROP_METHOD "http")
set(CTEST_DROP_SITE "cdash.inria.fr")
set(CTEST_DROP_LOCATION "/CDash/submit.php?project=faust")
set(CTEST_DROP_SITE_CDASH TRUE)

set(CTEST_FULL_OUTPUT TRUE)

