
% ==========================================
%> Prints the FAµST license.
% ==========================================
function license()
	disp('% License:')
	disp(' Copyright (2019):	Hakim Hadj-djilani, Nicolas Bellot, Adrien Leman, Thomas Gautrais, Luc Le Magoarou, Remi Gribonval')
	disp('			INRIA Rennes, FRANCE')
	disp('			http://www.inria.fr/')
	disp('')
	disp(' The FAuST Toolbox is distributed under the terms of the GNU Affero')
	disp(' General Public License.')
	disp(' This program is free software: you can redistribute it and/or modify')
	disp(' it under the terms of the GNU Affero General Public License as published')
	disp(' by the Free Software Foundation.')
	disp('')
	disp(' This program is distributed in the hope that it will be useful, but')
	disp(' WITHOUT ANY WARRANTY; without even the implied warranty of')
	disp(' MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.')
	disp(' See the GNU Affero General Public License for more details.')
	disp('')
	disp(' You should have received a copy of the GNU Affero General Public License')
	disp(' along with F program.  If not, see <http://www.gnu.org/licenses/>.')
	disp('')
	disp('% Contacts:')
	disp('   Remi Gribonval	: remi.gribonval@inria.fr')
	disp('   Hakim Hadj-dji. : hakim.hadj-djilani@inria.fr')
	disp('   Nicolas Bellot	: nicolas.bellot@inria.fr')
	disp('   Adrien Leman	: adrien.leman@inria.fr')
	disp('   Thomas Gautrais : thomas.gautrais@inria.fr')
	disp('   Luc Le Magoarou	: luc.le-magoarou@inria.fr')
	disp('')
	disp('% References:')
	disp(' [1]	Le Magoarou L. and Gribonval R., "Flexible multi-layer sparse')
	disp('	approximations of matrices and applications", Journal of Selected')
	disp('	Topics in Signal Processing, 2016.')
	disp('	<https://hal.archives-ouvertes.fr/hal-01167948v1>')
	disp('%')
end
