
% ==========================================
%> Prints the FAuST license.
% ==========================================
function license()
	disp('')
	disp(' Copyright (c) 2015-2023, Inria and Authors:                                        ')
	disp('  (Researchers:) Rémi Gribonval, Luc Le Magoarou,                                   ')
	disp('  (Engineers:) Adrien Leman (2016), Nicolas Bellot(2015-2016),                      ')
	disp('  Thomas Gautrais (2015), Hakim Hadj-Djilani (2018-),                               ')
	disp('  Pascal Carrivain (2023-).                                                         ')
	disp('  All rights reserved.                                                              ')
	disp('                                                                                    ')
	disp('  BSD 3-clause License.                                                             ')
	disp('                                                                                    ')
	disp(' Redistribution and use in source and binary forms, with or without                 ')
	disp(' modification, are permitted provided that the following conditions are met:        ')
	disp('                                                                                    ')
	disp(' 1. Redistributions of source code must retain the above copyright notice, this     ')
	disp(' list of conditions and the following disclaimer.                                   ')
	disp('                                                                                    ')
	disp(' 2. Redistributions in binary form must reproduce the above copyright notice,       ')
	disp('     this list of conditions and the following disclaimer in the documentation      ')
	disp('     and/or other materials provided with the distribution.                         ')
	disp('                                                                                    ')
	disp(' 3. Neither the name of the copyright holder nor the names of its                   ')
	disp(' contributors may be used to endorse or promote products derived from this          ')
	disp(' software without specific prior written permission.                                ')
	disp('                                                                                    ')
	disp(' THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"        ')
	disp(' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE          ')
	disp(' IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE         ')
	disp(' ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE          ')
	disp(' LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR                ')
	disp(' CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF               ')
	disp('         SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR            ')
	disp('         BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF                 ')
	disp(' LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING               ')
	disp('         NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS         ')
	disp(' SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.                       ')
	disp('')
end
