macro(check_external_libraries LIBRARY_NAME LIBRARY_FILE IS_NECESSARY)
	if(NOT ${ARGC} EQUAL 3)
		message(FATAL_ERROR "Wrong number of arguments in check_external_libraries macro")
	endif()
	find_library(${LIBRARY_FILE} ${LIBRARY_NAME} PATHS ${LIBRARY_PATH_LIST})
	if(${LIBRARY_FILE})
		message(STATUS "${LIBRARY_NAME} library found")
	else()
		message(STATUS "${LIBRARY_FILE} has not been set")
		if(${IS_NECESSARY})
			message(FATAL_ERROR "${LIBRARY_NAME} library not found !!!")
		else()
			message(STATUS "${LIBRARY_NAME} library not found !!!")
		endif()
	endif()
endmacro()
