macro(check_external_libraries LIBRARY_NAME LIBRARY_FILE IS_NECESSARY)
	if(NOT ${ARGC} EQUAL 3)
		message(FATAL_ERROR "Wrong number of arguments in check_external_libraries macro")
	endif()
	find_library(${LIBRARY_FILE} ${LIBRARY_NAME} PATHS ${LIBRARY_PATH_LIST} NO_DEFAULT_PATH)
	if(${LIBRARY_FILE})
		message(STATUS "${LIBRARY_NAME} library found")
	else()
		#message(STATUS "${LIBRARY_FILE} has not been set")
		if(${IS_NECESSARY})
			message(FATAL_ERROR "${LIBRARY_NAME} library not found !!!")
		else()
			message(STATUS "${LIBRARY_NAME} library not found in the selected directory.")
		endif()
	endif()
endmacro()


macro(check_external_includes INCLUDE_NAME INCLUDE_FILE IS_NECESSARY)
	if(NOT ${ARGC} EQUAL 3)
		message(FATAL_ERROR "Wrong number of arguments in check_external_includes macro")
	endif()
	find_path(${INCLUDE_FILE} NAMES ${INCLUDE_NAME} PATHS ${INCLUDE_PATH_LIST} NO_DEFAULT_PATH)
	if(${INCLUDE_FILE})
		message(STATUS "${INCLUDE_NAME} header found")
	else()
		#message(STATUS "${INCLUDE_FILE} has not been set")
		if(${IS_NECESSARY})
			message(FATAL_ERROR "${INCLUDE_NAME} header not found !!!")
		else()
			message(STATUS "${INCLUDE_NAME} header not found in the selected directory.")
		endif()
	endif()
endmacro()


