# SOURCE DIRECTORIES
set(FAUST_MATRIX_SRC_DIR ${PROJECT_SOURCE_DIR}/matrix)
set(FAUST_FAUSTCORE_SRC_DIR ${PROJECT_SOURCE_DIR}/faust_core)
set(FAUST_MATIO_SRC_DIR ${PROJECT_SOURCE_DIR}/init_from_matlab)
set(FAUST_PALM4MSA_SRC_DIR ${PROJECT_SOURCE_DIR}/palm4MSA)
set(FAUST_PALM4MSATEST_SRC_DIR ${PROJECT_SOURCE_DIR}/palm4MSA/test)
set(FAUST_MEXINTERFACE_SRC_DIR ${PROJECT_SOURCE_DIR}/interface_matlab)
set(FAUST_MEXINTERFACETOOLS_SRC_DIR ${FAUST_MEXINTERFACE_SRC_DIR}/tools)

# BINARY DIRECTORIES
set(FAUST_MATRIX_BIN_DIR ${PROJECT_BINARY_DIR}/matrix)
set(FAUST_FAUSTCORE_BIN_DIR ${PROJECT_BINARY_DIR}/faust_core)
set(FAUST_MATIO_BIN_DIR ${PROJECT_BINARY_DIR}/testing/init_from_matlab)
set(FAUST_PALM4MSA_BIN_DIR ${PROJECT_BINARY_DIR}/palm4MSA)
set(FAUST_PALM4MSATEST_BIN_DIR ${PROJECT_BINARY_DIR}/testing)
set(FAUST_MEXINTERFACE_BIN_DIR ${PROJECT_BINARY_DIR}/interface_matlab)
set(FAUST_MEXINTERFACETOOLS_BIN_DIR ${FAUST_MEXINTERFACE_BIN_DIR}/tools)

# TARGETS

set(FAUST_MATRIX_TARGET matrix)
set(FAUST_PALM4MSA_TARGET palm4MSA)
set(FAUST_FAUSTCORE_TARGET faust_core)
